/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wahib
 */
public class addMobil extends javax.swing.JPanel {

    /**
     * Creates new form addMobil
     */
    public addMobil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtTahunPembuatan = new javax.swing.JTextField();
        TxtKodeMobil = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtHargaSewa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtNoMesin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtTypeMobil = new javax.swing.JTextField();
        TxtWarnaMobil = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtNoRangka = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        resolusi = new javax.swing.JLabel();

        setBackground(new java.awt.Color(52, 73, 94));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TAMBAH DATA MOBIL");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 280, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kode Mobil");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 130, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Harga Sewa");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 110, 30));
        add(TxtTahunPembuatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 290, 40));

        TxtKodeMobil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtKodeMobilKeyPressed(evt);
            }
        });
        add(TxtKodeMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 290, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No. Mesin");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 100, 40));
        add(TxtHargaSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 290, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tahun Pembuatan");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 160, 30));
        add(TxtNoMesin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 290, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Warna Mobil");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 110, 40));
        add(TxtTypeMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 290, 40));
        add(TxtWarnaMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 290, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Status");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 70, 40));
        add(TxtNoRangka, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 290, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Plat Nomor");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 100, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Type Mobil");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 120, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baru", "Standard", "Jadul" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 150, 40));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("CANCEL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("EXIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, -1, -1));
        add(resolusi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 680));
    }// </editor-fold>//GEN-END:initComponents

    private void TxtKodeMobilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtKodeMobilKeyPressed
        // TODO add your handling code here:
//        try {
//            Connection c=ClassDB.getkoneksi();
//            Statement s= c.createStatement();
//            String sql="Select * from tblmobil where kd_mobil='" + this.TxtKodeMobil.getText() + "'";
//            ResultSet r=s.executeQuery(sql);
//
//            while (r.next()){
//                this.TxtTypeMobil.setText(r.getString("type_mobil"));
//                this.TxtHargaSewa.setText(r.getString("hrg_sewa"));
//                this.TxtNoMesin.setText(r.getString("no_mesin"));
//                this.TxtNoRangka.setText(r.getString("no_rangka"));
//                this.TxtStatus.setText(r.getString("status"));
//                this.TxtTahunPembuatan.setText(r.getString("thn_pemb"));
//                this.TxtWarnaMobil.setText(r.getString("warna_mobil"));
//            }
//            r.close();
//            s.close();
//
//        }catch(SQLException e) {
//            System.out.println("Terjadi kesalahan");
//        }
    }//GEN-LAST:event_TxtKodeMobilKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String kd=this.TxtKodeMobil.getText();
        String tm=this.TxtTypeMobil.getText();
        String nm=this.TxtNoMesin.getText();
        String nr=this.TxtNoRangka.getText();
        String wm=this.TxtWarnaMobil.getText();
        String tp=this.TxtTahunPembuatan.getText();
        String hs=this.TxtHargaSewa.getText();

//        if("".equals(this.TxtKodeMobil.getText()) || ("".equals(this.TxtTypeMobil.getText())) || ("".equals(this.TxtNoMesin.getText())) || ("".equals(this.TxtNoRangka.getText())) || ("".equals(this.TxtWarnaMobil.getText())) || ("".equals(this.TxtTahunPembuatan.getText())))
//        {
//            JOptionPane.showMessageDialog(this, "Lengkapi data");
//        }else{
//            try {
//
//                Connection c=ClassDB.getkoneksi();
//                Statement s= c.createStatement();
//                String sql="Update tblmobil Set type_mobil=?,no_mesin=?,no_rangka=?,warna_mobil=?,thn_pemb=?,hrg_sewa=? Where kd_mobil=?";
//                ResultSet r=s.executeQuery(sql);
//
//                PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
//                p.setString(7, kd);
//                p.setString(1, tm);
//                p.setString(2, nm);
//                p.setString(3, nr);
//                p.setString(4, wm);
//                p.setString(5, tp);
//                p.setString(6, hs);
//
//                p.executeUpdate();
//                p.close();
//                JOptionPane.showMessageDialog(this, "Sukses Edit data");
//            }catch(SQLException e) {
//                System.out.println("Terjadi kesalahan");
//            }finally{
//                HapusTeks();
//            }
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String kd=this.TxtKodeMobil.getText();
        String tm=this.TxtTypeMobil.getText();
        String nm=this.TxtNoMesin.getText();
        String nr=this.TxtNoRangka.getText();
        String wm=this.TxtWarnaMobil.getText();
        String tp=this.TxtTahunPembuatan.getText();
        String hs=this.TxtHargaSewa.getText();
        String st="Free";
//        if("".equals(this.TxtKodeMobil.getText()) || ("".equals(this.TxtTypeMobil.getText())) || ("".equals(this.TxtNoMesin.getText())) || ("".equals(this.TxtNoRangka.getText())) || ("".equals(this.TxtWarnaMobil.getText())) || ("".equals(this.TxtTahunPembuatan.getText())))
//        {
//            JOptionPane.showMessageDialog(this, "Lengkapi data");
//        }else{
//            try {
//
//                Connection c=ClassDB.getkoneksi();
//                Statement s= c.createStatement();
//                String sql="Insert into tblmobil values (?,?,?,?,?,?,?,?)";
//
//                PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
//                p.setString(1, kd);
//                p.setString(2, tm);
//                p.setString(3, nm);
//                p.setString(4, nr);
//                p.setString(5, wm);
//                p.setString(6, tp);
//                p.setString(7, hs);
//                p.setString(8, st);
//                p.executeUpdate();
//                p.close();
//                JOptionPane.showMessageDialog(this, "Sukses Tambah data");
//            }catch(SQLException e) {
//                System.out.println("Terjadi kesalahan " + e);
//            }finally{
//                HapusTeks();
//            }
//        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String kd=this.TxtKodeMobil.getText();
//        if("".equals(this.TxtKodeMobil.getText()) || ("".equals(this.TxtTypeMobil.getText())) || ("".equals(this.TxtNoMesin.getText())) || ("".equals(this.TxtNoRangka.getText())) || ("".equals(this.TxtWarnaMobil.getText())) || ("".equals(this.TxtTahunPembuatan.getText())))
//        {
//            JOptionPane.showMessageDialog(this, "Lengkapi data");
//        }else{
//            try {
//                Connection c=ClassDB.getkoneksi();
//                String sql = "DELETE From tblmobil  WHERE kd_mobil=?";
//                PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
//                p.setString(1, kd);
//                p.executeUpdate();
//                p.close();
//                JOptionPane.showMessageDialog(this, "Sukses Hapus data");
//            }catch(SQLException e){
//                System.out.println("Terjadi kesalahan");
//            }finally{
//                HapusTeks();
//            }
//        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
//        HapusTeks();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
//        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtHargaSewa;
    private javax.swing.JTextField TxtKodeMobil;
    private javax.swing.JTextField TxtNoMesin;
    private javax.swing.JTextField TxtNoRangka;
    private javax.swing.JTextField TxtTahunPembuatan;
    private javax.swing.JTextField TxtTypeMobil;
    private javax.swing.JTextField TxtWarnaMobil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resolusi;
    // End of variables declaration//GEN-END:variables
}
