/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wahib
 */
public class addPeminjam extends javax.swing.JPanel {

    /**
     * Creates new form addPeminjam
     */
    public addPeminjam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtIDPeminjam = new javax.swing.JTextField();
        TxtNamaPeminjam = new javax.swing.JTextField();
        TxtAlamat = new javax.swing.JTextField();
        TxtNoHP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtJenisKelamin = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        resolusi = new javax.swing.JLabel();

        setBackground(new java.awt.Color(52, 73, 94));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("No. HP");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));
        add(TxtIDPeminjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 190, 40));
        add(TxtNamaPeminjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 190, 40));
        add(TxtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 340, 40));
        add(TxtNoHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 250, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ENTRY SEWA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        TxtJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-Laki", "Perempuan" }));
        add(TxtJenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 139, 27));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jln. Jawa 7 no. 54 (Belakang Kampus UNEJ FISIP) Telp. 0351-21716 , HP. 081363983142");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("CANCEL");

        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("EXIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Peminjam");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Peminjam");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jenis Kelamin");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));
        add(resolusi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 680));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        String kd=this.TxtIDPeminjam.getText();
//        String np=this.TxtNamaPeminjam.getText();
//        String jk=(String) this.TxtJenisKelamin.getSelectedItem();
//        String al=this.TxtAlamat.getText();
//        String tlp=this.TxtNoHP.getText();
//        if("".equals(kd) || ("".equals(np)) || ("".equals(jk)) || ("".equals(al)) || ("".equals(tlp)))
//        {
//            JOptionPane.showMessageDialog(this, "Lengkapi data");
//        }else{
//            try {
//
//                Connection c=ClassDB.getkoneksi();
//                Statement s= c.createStatement();
//                String sql="Insert into tblpeminjam values (?,?,?,?,?)";
//
//                PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
//                p.setString(1, kd);
//                p.setString(2, np);
//                p.setString(3, jk);
//                p.setString(4, al);
//                p.setString(5, tlp);
//
//                p.executeUpdate();
//                p.close();
//                JOptionPane.showMessageDialog(this, "Sukses Tambah data");
//            }catch(SQLException e) {
//                System.out.println("Terjadi kesalahan " + e);
//            }finally{
//                HapusTeks();
//            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        String kd=this.TxtIDPeminjam.getText();
//        String np=this.TxtNamaPeminjam.getText();
//        String jk=(String) this.TxtJenisKelamin.getSelectedItem();
//        String al=this.TxtAlamat.getText();
//        String tlp=this.TxtNoHP.getText();
//        if("".equals(kd) || ("".equals(np)) || ("".equals(jk)) || ("".equals(al)) || ("".equals(tlp)))
//        {
//            JOptionPane.showMessageDialog(this, "Lengkapi data");
//        }else{
//            try {
//
//                Connection c=ClassDB.getkoneksi();
//                Statement s= c.createStatement();
//                String sql="Update tblpeminjam Set nama=?,jekel=?,alamat=?,no_hp=? Where id_peminjam=?)";
//
//                PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
//                p.setString(5, kd);
//                p.setString(1, np);
//                p.setString(2, jk);
//                p.setString(3, al);
//                p.setString(4, tlp);
//
//                p.executeUpdate();
//                p.close();
//                JOptionPane.showMessageDialog(this, "Sukses Update data");
//            }catch(SQLException e) {
//                System.out.println("Terjadi kesalahan " + e);
//            }finally{
//                HapusTeks();
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
//        String kd=this.TxtIDPeminjam.getText();
//        String np=this.TxtNamaPeminjam.getText();
//        String jk=(String) this.TxtJenisKelamin.getSelectedItem();
//        String al=this.TxtAlamat.getText();
//        String tlp=this.TxtNoHP.getText();
//        if("".equals(kd) || ("".equals(np)) || ("".equals(jk)) || ("".equals(al)) || ("".equals(tlp)))
//        {
//            JOptionPane.showMessageDialog(this, "Lengkapi data");
//        }else{
//            try {
//
//                Connection c=ClassDB.getkoneksi();
//                Statement s= c.createStatement();
//                String sql="Delete from tblpeminjam Where id_peminjam=?";
//
//                PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
//                p.setString(1, kd);
//
//                p.executeUpdate();
//                p.close();
//                JOptionPane.showMessageDialog(this, "Sukses Hapus data");
//            }catch(SQLException e) {
//                System.out.println("Terjadi kesalahan " + e);
//            }finally{
//                HapusTeks();
//            }
//        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
//        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtAlamat;
    private javax.swing.JTextField TxtIDPeminjam;
    private javax.swing.JComboBox TxtJenisKelamin;
    private javax.swing.JTextField TxtNamaPeminjam;
    private javax.swing.JTextField TxtNoHP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel resolusi;
    // End of variables declaration//GEN-END:variables
}
