
import java.text.DateFormat;
import java.text.SimpleDateFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wahib
 */
public class awal extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    DateFormat d = DateFormat.getDateInstance();
    public awal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleHeader = new javax.swing.JLabel();
        setting = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        cart = new javax.swing.JLabel();
        checkout = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        jumlah = new javax.swing.JLabel();
        dropdown = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        setting1 = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        body = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RENTAL MOBIL - JAYA MAKMUR");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleHeader.setFont(new java.awt.Font("Segoe UI Semibold", 0, 33)); // NOI18N
        titleHeader.setForeground(new java.awt.Color(255, 255, 255));
        titleHeader.setText("RENTAL MOBIL - JAYA MAKMUR");
        getContentPane().add(titleHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 550, 50));

        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Settings_40px.png"))); // NOI18N
        getContentPane().add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 60, 50));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Menu_40px.png"))); // NOI18N
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 50));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Home_40px.png"))); // NOI18N
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, 50));

        cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Shopping_Cart_40px.png"))); // NOI18N
        getContentPane().add(cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 50, 50));

        checkout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Money_40px.png"))); // NOI18N
        getContentPane().add(checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 60, 50));

        Name.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Admin");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 50, 80, 40));

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Contacts_40px.png"))); // NOI18N
        getContentPane().add(userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 40, 50));

        jumlah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8__Circled_2_20px.png"))); // NOI18N
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 20, 20));

        dropdown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Logout_Rounded_Left_40px.png"))); // NOI18N
        getContentPane().add(dropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 40, 50));

        welcomeLbl.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLbl.setText("Selamat datang");
        getContentPane().add(welcomeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, 120, 30));

        setting1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Car_40px.png"))); // NOI18N
        getContentPane().add(setting1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 60, 50));

        sidebar.setBackground(new java.awt.Color(44, 62, 80));

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 680));

        header.setBackground(new java.awt.Color(34, 49, 63));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 1050, 90));

        body.setBackground(new java.awt.Color(52, 73, 94));

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 1050, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new awal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JPanel body;
    private javax.swing.JLabel cart;
    private javax.swing.JLabel checkout;
    private javax.swing.JLabel dropdown;
    private javax.swing.JPanel header;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jumlah;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel setting;
    private javax.swing.JLabel setting1;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel titleHeader;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
