import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
public class formPeminjaman extends javax.swing.JPanel {

    /**
     * Creates new form formPemesanan
     */
    SimpleDateFormat d;
    public formPeminjaman() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        merk = new javax.swing.JComboBox<>();
        orderLbl2 = new javax.swing.JLabel();
        id_pelanggan2 = new javax.swing.JTextField();
        orderLbl3 = new javax.swing.JLabel();
        pelangganLbl = new javax.swing.JLabel();
        payoutbtn = new javax.swing.JButton();
        payoutbtn1 = new javax.swing.JButton();
        tglOrder = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        orderLbl = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        harga = new javax.swing.JLabel();
        jml = new javax.swing.JTextField();
        tglKembali = new com.toedter.calendar.JDateChooser();
        orderLbl1 = new javax.swing.JLabel();
        orderLbl4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPinjam = new javax.swing.JTable();
        pelangganLbl1 = new javax.swing.JLabel();
        resolusi = new javax.swing.JLabel();
        pelangganLbl2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(52, 73, 94));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        merk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Honda Jazz", "Kijang Inova", "Suzuki APV", "Toyota Veloz", "Toyota Calya" }));
        merk.setBorder(null);
        merk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merkActionPerformed(evt);
            }
        });
        add(merk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 290, 40));

        orderLbl2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        orderLbl2.setForeground(new java.awt.Color(255, 255, 255));
        orderLbl2.setText("TANGGAL KEMBALI");
        add(orderLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 190, 40));

        id_pelanggan2.setBackground(new java.awt.Color(52, 73, 94));
        id_pelanggan2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        id_pelanggan2.setForeground(new java.awt.Color(255, 255, 255));
        id_pelanggan2.setBorder(null);
        add(id_pelanggan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 290, 30));

        orderLbl3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        orderLbl3.setForeground(new java.awt.Color(255, 255, 255));
        orderLbl3.setText("MERK MOBIL");
        add(orderLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 120, 30));

        pelangganLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        pelangganLbl.setForeground(new java.awt.Color(255, 255, 255));
        pelangganLbl.setText("TAMBAH PEMINJAMAN");
        add(pelangganLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 220, 30));

        payoutbtn.setBackground(new java.awt.Color(92, 151, 191));
        payoutbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        payoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        payoutbtn.setText("PAYOUT");
        payoutbtn.setBorder(null);
        add(payoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 110, 40));

        payoutbtn1.setBackground(new java.awt.Color(92, 151, 191));
        payoutbtn1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        payoutbtn1.setForeground(new java.awt.Color(255, 255, 255));
        payoutbtn1.setText("CETAK STRUK");
        payoutbtn1.setBorder(null);
        add(payoutbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, 140, 40));
        add(tglOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 290, 40));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 290, 10));

        orderLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        orderLbl.setForeground(new java.awt.Color(255, 255, 255));
        orderLbl.setText("HARGA");
        add(orderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 100, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 290, 10));

        harga.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        harga.setForeground(new java.awt.Color(255, 255, 255));
        add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 270, 40));

        jml.setBackground(new java.awt.Color(52, 73, 94));
        jml.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jml.setForeground(new java.awt.Color(255, 255, 255));
        jml.setBorder(null);
        add(jml, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 290, 30));
        add(tglKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 290, 40));

        orderLbl1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        orderLbl1.setForeground(new java.awt.Color(255, 255, 255));
        orderLbl1.setText("TANGGAL ORDER");
        add(orderLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 160, 30));

        orderLbl4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        orderLbl4.setForeground(new java.awt.Color(255, 255, 255));
        orderLbl4.setText("JUMLAH MOBIL");
        add(orderLbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 150, 30));

        tblPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_order", "Nama", "Merk Mobil", "Jumlah", "Harga"
            }
        ));
        tblPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPinjamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPinjam);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 490, 150));

        pelangganLbl1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        pelangganLbl1.setForeground(new java.awt.Color(255, 255, 255));
        pelangganLbl1.setText("NAMA");
        add(pelangganLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, 30));
        add(resolusi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 680));

        pelangganLbl2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        pelangganLbl2.setForeground(new java.awt.Color(255, 255, 255));
        pelangganLbl2.setText("LIST PEMINJAMAN");
        add(pelangganLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 160, 30));
    }// </editor-fold>//GEN-END:initComponents
        
    private void merkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merkActionPerformed
        String mobil = (String) merk.getSelectedItem();
        int jumlah = Integer.parseInt(jml.getText());
        if (mobil.equalsIgnoreCase("Honda Jazz")) {
            int h1 = 120000 * jumlah;
            harga.setText(""+h1);
        }
        else if (mobil.equalsIgnoreCase("Suzuki APV")) {
            int h1 = 150000 * jumlah;
            harga.setText(""+h1);
        }
        else {
            System.out.println("Salah");
        }
    }//GEN-LAST:event_merkActionPerformed

    private void tblPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPinjamMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_tblPinjamMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel harga;
    private javax.swing.JTextField id_pelanggan2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jml;
    private javax.swing.JComboBox<String> merk;
    private javax.swing.JLabel orderLbl;
    private javax.swing.JLabel orderLbl1;
    private javax.swing.JLabel orderLbl2;
    private javax.swing.JLabel orderLbl3;
    private javax.swing.JLabel orderLbl4;
    private javax.swing.JButton payoutbtn;
    private javax.swing.JButton payoutbtn1;
    private javax.swing.JLabel pelangganLbl;
    private javax.swing.JLabel pelangganLbl1;
    private javax.swing.JLabel pelangganLbl2;
    private javax.swing.JLabel resolusi;
    private javax.swing.JTable tblPinjam;
    private com.toedter.calendar.JDateChooser tglKembali;
    private com.toedter.calendar.JDateChooser tglOrder;
    // End of variables declaration//GEN-END:variables
}
