/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wahib
 */
public class formPengembalian extends javax.swing.JPanel {

    /**
     * Creates new form formPengembalian
     */
    public formPengembalian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pelunasan = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        totalLbl = new javax.swing.JLabel();
        id_pelanggan3 = new javax.swing.JTextField();
        pelangganLbl2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPinjam = new javax.swing.JTable();
        pelangganLbl3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pelangganLbl4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(52, 73, 94));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 290, 10));

        totalLbl.setForeground(new java.awt.Color(255, 255, 255));
        add(totalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 160, 30));

        id_pelanggan3.setBackground(new java.awt.Color(52, 73, 94));
        id_pelanggan3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        id_pelanggan3.setForeground(new java.awt.Color(255, 255, 255));
        id_pelanggan3.setBorder(null);
        add(id_pelanggan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 290, 30));

        pelangganLbl2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        pelangganLbl2.setForeground(new java.awt.Color(255, 255, 255));
        pelangganLbl2.setText("TOTAL");
        add(pelangganLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 80, 40));

        tblPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_peminjaman", "Nama", "Merk Mobil", "Jumlah", "Harga", "tglPinjam", "tglKembali"
            }
        ));
        tblPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPinjamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPinjam);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 700, 150));

        pelangganLbl3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        pelangganLbl3.setForeground(new java.awt.Color(255, 255, 255));
        pelangganLbl3.setText("ID User");
        add(pelangganLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 140, 30));

        jButton1.setText("Batal");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 90, 40));

        jButton2.setText("Simpan");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 90, 40));

        pelangganLbl4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        pelangganLbl4.setForeground(new java.awt.Color(255, 255, 255));
        pelangganLbl4.setText("PENGEMBALIAN");
        add(pelangganLbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 140, 40));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 680));
    }// </editor-fold>//GEN-END:initComponents

    private void tblPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPinjamMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblPinjamMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id_pelanggan3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel pelangganLbl2;
    private javax.swing.JLabel pelangganLbl3;
    private javax.swing.JLabel pelangganLbl4;
    private javax.swing.ButtonGroup pelunasan;
    private javax.swing.JTable tblPinjam;
    private javax.swing.JLabel totalLbl;
    // End of variables declaration//GEN-END:variables
}
