
import java.text.DateFormat;
import java.text.SimpleDateFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wahib
 */
public class home1 extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    DateFormat d = DateFormat.getDateInstance();
    public home1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleHeader = new javax.swing.JLabel();
        setting = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        checkout = new javax.swing.JLabel();
        orderLbl = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        dropdown = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        pelangganLbl = new javax.swing.JLabel();
        orderLbl1 = new javax.swing.JLabel();
        orderLbl2 = new javax.swing.JLabel();
        merk = new javax.swing.JComboBox<>();
        orderLbl3 = new javax.swing.JLabel();
        orderLbl4 = new javax.swing.JLabel();
        setting1 = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jml = new javax.swing.JTextField();
        id_pelanggan2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        tglKembali = new com.toedter.calendar.JDateChooser();
        tglOrder = new com.toedter.calendar.JDateChooser();
        payoutbtn = new javax.swing.JButton();
        resolusi = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        body = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RENTAL MOBIL - JAYA MAKMUR");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleHeader.setFont(new java.awt.Font("Segoe UI Semibold", 0, 33)); // NOI18N
        titleHeader.setForeground(new java.awt.Color(255, 255, 255));
        titleHeader.setText("RENTAL MOBIL - JAYA MAKMUR");
        getContentPane().add(titleHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 550, 50));

        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Settings_40px.png"))); // NOI18N
        getContentPane().add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 60, 50));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Menu_40px.png"))); // NOI18N
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 50));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Home_40px.png"))); // NOI18N
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, 50));

        checkout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Money_40px.png"))); // NOI18N
        getContentPane().add(checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 60, 50));

        orderLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        orderLbl.setForeground(new java.awt.Color(255, 255, 255));
        orderLbl.setText("HARGA");
        getContentPane().add(orderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 190, 30));

        Name.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Admin");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 50, 80, 40));

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Contacts_40px.png"))); // NOI18N
        getContentPane().add(userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 40, 50));

        dropdown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Logout_Rounded_Left_40px.png"))); // NOI18N
        getContentPane().add(dropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 40, 50));

        welcomeLbl.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLbl.setText("Selamat datang");
        getContentPane().add(welcomeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, 120, 30));

        pelangganLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        pelangganLbl.setForeground(new java.awt.Color(255, 255, 255));
        pelangganLbl.setText("NAMA");
        getContentPane().add(pelangganLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 190, 30));

        orderLbl1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        orderLbl1.setForeground(new java.awt.Color(255, 255, 255));
        orderLbl1.setText("TANGGAL ORDER");
        getContentPane().add(orderLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 210, 30));

        orderLbl2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        orderLbl2.setForeground(new java.awt.Color(255, 255, 255));
        orderLbl2.setText("TANGGAL KEMBALI");
        getContentPane().add(orderLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 210, 30));

        merk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Honda Jazz", "Kijang Inova", "Suzuki APV", "Toyota Veloz", "Toyota Calya" }));
        merk.setSelectedItem(getIconImage());
        merk.setBorder(null);
        merk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merkActionPerformed(evt);
            }
        });
        getContentPane().add(merk, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 290, 40));

        orderLbl3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        orderLbl3.setForeground(new java.awt.Color(255, 255, 255));
        orderLbl3.setText("MERK MOBIL");
        getContentPane().add(orderLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 190, 30));

        orderLbl4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        orderLbl4.setForeground(new java.awt.Color(255, 255, 255));
        orderLbl4.setText("JUMLAH MOBIL");
        getContentPane().add(orderLbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 190, 30));

        setting1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Car_40px.png"))); // NOI18N
        getContentPane().add(setting1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 60, 50));

        harga.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        harga.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 270, 40));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 290, 10));

        jml.setBackground(new java.awt.Color(52, 73, 94));
        jml.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jml.setForeground(new java.awt.Color(255, 255, 255));
        jml.setBorder(null);
        getContentPane().add(jml, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 290, 30));

        id_pelanggan2.setBackground(new java.awt.Color(52, 73, 94));
        id_pelanggan2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        id_pelanggan2.setForeground(new java.awt.Color(255, 255, 255));
        id_pelanggan2.setBorder(null);
        getContentPane().add(id_pelanggan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 290, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 290, 10));
        getContentPane().add(tglKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 290, 40));
        getContentPane().add(tglOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 290, 40));

        payoutbtn.setBackground(new java.awt.Color(92, 151, 191));
        payoutbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        payoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        payoutbtn.setText("PAYOUT");
        payoutbtn.setBorder(null);
        getContentPane().add(payoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, 110, 40));

        resolusi.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        resolusi.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(resolusi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 677));

        sidebar.setBackground(new java.awt.Color(44, 62, 80));

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 680));

        header.setBackground(new java.awt.Color(34, 49, 63));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 1050, 90));

        body.setBackground(new java.awt.Color(52, 73, 94));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 1050, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void merkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merkActionPerformed
        d = new SimpleDateFormat("dd");
        String mobil = (String) merk.getSelectedItem();
        String x = d.format(tglOrder.getDate());
        String y = d.format(tglKembali.getDate());
        int xx = Integer.parseInt(x);
        int yy = Integer.parseInt(y);
        int total;
        int jumlah = Integer.parseInt(jml.getText());
        if (mobil.equalsIgnoreCase("Honda Jazz")) {
            total = 10000 * jumlah;
            harga.setText(""+total);
        }
    }//GEN-LAST:event_merkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JPanel body;
    private javax.swing.JLabel checkout;
    private javax.swing.JLabel dropdown;
    private javax.swing.JLabel harga;
    private javax.swing.JPanel header;
    private javax.swing.JLabel home;
    private javax.swing.JTextField id_pelanggan2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jml;
    private javax.swing.JLabel menu;
    private javax.swing.JComboBox<String> merk;
    private javax.swing.JLabel orderLbl;
    private javax.swing.JLabel orderLbl1;
    private javax.swing.JLabel orderLbl2;
    private javax.swing.JLabel orderLbl3;
    private javax.swing.JLabel orderLbl4;
    private javax.swing.JButton payoutbtn;
    private javax.swing.JLabel pelangganLbl;
    private javax.swing.JLabel resolusi;
    private javax.swing.JLabel setting;
    private javax.swing.JLabel setting1;
    private javax.swing.JPanel sidebar;
    private com.toedter.calendar.JDateChooser tglKembali;
    private com.toedter.calendar.JDateChooser tglOrder;
    private javax.swing.JLabel titleHeader;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
