
import java.awt.GridBagLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wahib
 */
public class home extends javax.swing.JFrame {

    GridBagLayout layout = new GridBagLayout();
    DateFormat d = DateFormat.getDateInstance();
    addMobil addCar;
    addPeminjam addCustomer;
    dashboard dash;
    formPeminjaman pesan; 
    public home() {
        initComponents();
        addCar = new addMobil();
        addCustomer = new addPeminjam();
        dash = new dashboard();
        pesan = new formPeminjaman();
        body.setLayout(layout);
        body.add(addCar);
        body.add(addCustomer);
        body.add(dash);
        body.add(pesan);
        dash.setVisible(true);
        addCar.setVisible(false);
        addCustomer.setVisible(false);
        pesan.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        cart = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        checkout = new javax.swing.JLabel();
        setting = new javax.swing.JLabel();
        setting1 = new javax.swing.JLabel();
        titleHeader = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        userIcon1 = new javax.swing.JLabel();
        Name1 = new javax.swing.JLabel();
        welcomeLbl1 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        dropdown = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        resolusi = new javax.swing.JLabel();
        itemLapData = new javax.swing.JMenuBar();
        entryData = new javax.swing.JMenu();
        itemMobil = new javax.swing.JMenuItem();
        itemPeminjam = new javax.swing.JMenuItem();
        Transaksi = new javax.swing.JMenu();
        itemPeminjaman = new javax.swing.JMenuItem();
        itemPengembalian = new javax.swing.JMenuItem();
        itemLaporan = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        lapPeminjaman = new javax.swing.JMenuItem();
        lapPendapatan = new javax.swing.JMenuItem();
        itemBantuan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RENTAL MOBIL - JAYA MAKMUR");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(44, 62, 80));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Plus_Math_40px.png"))); // NOI18N
        sidebar.add(cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 50, 50));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Home_40px.png"))); // NOI18N
        sidebar.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, 50));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Menu_40px.png"))); // NOI18N
        sidebar.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 50));

        checkout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Money_40px.png"))); // NOI18N
        sidebar.add(checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 60, 50));

        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Settings_40px.png"))); // NOI18N
        sidebar.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 60, 50));

        setting1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Car_40px.png"))); // NOI18N
        sidebar.add(setting1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 60, 50));

        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 650));

        titleHeader.setFont(new java.awt.Font("Segoe UI Semibold", 0, 33)); // NOI18N
        titleHeader.setForeground(new java.awt.Color(255, 255, 255));
        titleHeader.setText("RENTAL MOBIL - JAYA MAKMUR");
        getContentPane().add(titleHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 550, 50));

        header.setBackground(new java.awt.Color(34, 49, 63));

        userIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Contacts_40px.png"))); // NOI18N

        Name1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        Name1.setForeground(new java.awt.Color(255, 255, 255));
        Name1.setText("Admin");

        welcomeLbl1.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        welcomeLbl1.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLbl1.setText("Selamat datang");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(948, Short.MAX_VALUE)
                .addComponent(userIcon1)
                .addGap(10, 10, 10)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(userIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(welcomeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 90));

        Name.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Admin");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 50, 80, 40));

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Contacts_40px.png"))); // NOI18N
        getContentPane().add(userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 40, 50));

        dropdown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Logout_Rounded_Left_40px.png"))); // NOI18N
        getContentPane().add(dropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 50, 100));

        welcomeLbl.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLbl.setText("Selamat datang");
        getContentPane().add(welcomeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, 120, 30));

        harga.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        harga.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 270, 40));

        body.setBackground(new java.awt.Color(52, 73, 94));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resolusi.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        resolusi.setForeground(new java.awt.Color(255, 255, 255));
        body.add(resolusi, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -113, 1130, 670));

        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 1050, -1));

        itemLapData.setBorder(null);

        entryData.setText("Entry Data");

        itemMobil.setText("Entry Data Mobil");
        itemMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMobilActionPerformed(evt);
            }
        });
        entryData.add(itemMobil);

        itemPeminjam.setText("Entry Data Peminjam");
        itemPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPeminjamActionPerformed(evt);
            }
        });
        entryData.add(itemPeminjam);

        itemLapData.add(entryData);

        Transaksi.setText("Transaksi");

        itemPeminjaman.setText("Transaksi Peminjaman");
        itemPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPeminjamanActionPerformed(evt);
            }
        });
        Transaksi.add(itemPeminjaman);

        itemPengembalian.setText("Transaksi Pengembalian");
        Transaksi.add(itemPengembalian);

        itemLapData.add(Transaksi);

        itemLaporan.setText("Laporan");

        jMenu1.setText("Laporan Data");

        lapPeminjaman.setText("Peminjaman");
        jMenu1.add(lapPeminjaman);

        lapPendapatan.setText("Pendapatan");
        jMenu1.add(lapPendapatan);

        itemLaporan.add(jMenu1);

        itemLapData.add(itemLaporan);

        itemBantuan.setText("Bantuan");
        itemLapData.add(itemBantuan);

        setJMenuBar(itemLapData);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMobilActionPerformed
        // TODO add your handling code here:
        addCar.setVisible(true);
        addCustomer.setVisible(false);
        dash.setVisible(false);
        pesan.setVisible(false);
    }//GEN-LAST:event_itemMobilActionPerformed

    private void itemPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPeminjamActionPerformed
        // TODO add your handling code here:
        addCar.setVisible(false);
        addCustomer.setVisible(true);
        dash.setVisible(false);
        pesan.setVisible(false);
    }//GEN-LAST:event_itemPeminjamActionPerformed

    private void itemPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPeminjamanActionPerformed
        // TODO add your handling code here:
        addCar.setVisible(false);
        addCustomer.setVisible(false);
        dash.setVisible(false);
        pesan.setVisible(true);
    }//GEN-LAST:event_itemPeminjamanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JMenu Transaksi;
    private javax.swing.JPanel body;
    private javax.swing.JLabel cart;
    private javax.swing.JLabel checkout;
    private javax.swing.JLabel dropdown;
    private javax.swing.JMenu entryData;
    private javax.swing.JLabel harga;
    private javax.swing.JPanel header;
    private javax.swing.JLabel home;
    private javax.swing.JMenu itemBantuan;
    private javax.swing.JMenuBar itemLapData;
    private javax.swing.JMenu itemLaporan;
    private javax.swing.JMenuItem itemMobil;
    private javax.swing.JMenuItem itemPeminjam;
    private javax.swing.JMenuItem itemPeminjaman;
    private javax.swing.JMenuItem itemPengembalian;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem lapPeminjaman;
    private javax.swing.JMenuItem lapPendapatan;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel resolusi;
    private javax.swing.JLabel setting;
    private javax.swing.JLabel setting1;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel titleHeader;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel userIcon1;
    private javax.swing.JLabel welcomeLbl;
    private javax.swing.JLabel welcomeLbl1;
    // End of variables declaration//GEN-END:variables
}
