package data;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wahib
 */
public class listPeminjaman extends javax.swing.JPanel {

    /**
     * Creates new form listPeminjaman
     */
    public listPeminjaman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pelangganLbl2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPinjam = new javax.swing.JTable();
        payoutbtn1 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        resolusi = new javax.swing.JLabel();

        setBackground(new java.awt.Color(52, 73, 94));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pelangganLbl2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        pelangganLbl2.setForeground(new java.awt.Color(255, 255, 255));
        pelangganLbl2.setText("LIST PEMINJAMAN");
        add(pelangganLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 160, 30));

        tblPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nama", "Merk Mobil", "Jumlah", "Harga", "tglPinjam", "tglKembali"
            }
        ));
        tblPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPinjamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPinjam);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 860, 290));

        payoutbtn1.setBackground(new java.awt.Color(92, 151, 191));
        payoutbtn1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        payoutbtn1.setForeground(new java.awt.Color(255, 255, 255));
        payoutbtn1.setText("CETAK ");
        payoutbtn1.setBorder(null);
        add(payoutbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 140, 40));

        backBtn.setBackground(new java.awt.Color(92, 151, 191));
        backBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("KEMBALI");
        backBtn.setBorder(null);
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 140, 40));
        add(resolusi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 680));
    }// </editor-fold>//GEN-END:initComponents

    private void tblPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPinjamMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblPinjamMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton payoutbtn1;
    private javax.swing.JLabel pelangganLbl2;
    private javax.swing.JLabel resolusi;
    private javax.swing.JTable tblPinjam;
    // End of variables declaration//GEN-END:variables
}
