package data;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wahib
 */
public class pendapatan extends javax.swing.JPanel {

    /**
     * Creates new form pendapatan
     */
    public pendapatan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblPinjam = new javax.swing.JTable();
        pelangganLbl2 = new javax.swing.JLabel();
        printBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        resolusi = new javax.swing.JLabel();

        setBackground(new java.awt.Color(52, 73, 94));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Tanggal", "jumlah order", "suzuki Apv", "honda jazz", "kijang apv", "toyota Veloz", "toyota calya", "total pendapatan"
            }
        ));
        tblPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPinjamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPinjam);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 850, 290));

        pelangganLbl2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        pelangganLbl2.setForeground(new java.awt.Color(255, 255, 255));
        pelangganLbl2.setText("Laporan Pendapatan");
        add(pelangganLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 230, 60));

        printBtn.setBackground(new java.awt.Color(92, 151, 191));
        printBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        printBtn.setForeground(new java.awt.Color(255, 255, 255));
        printBtn.setText("KEMBALI");
        printBtn.setBorder(null);
        add(printBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 140, 40));

        backBtn.setBackground(new java.awt.Color(92, 151, 191));
        backBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("CETAK");
        backBtn.setBorder(null);
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 450, 140, 40));
        add(resolusi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 680));
    }// </editor-fold>//GEN-END:initComponents

    private void tblPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPinjamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPinjamMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel pelangganLbl2;
    private javax.swing.JButton printBtn;
    private javax.swing.JLabel resolusi;
    private javax.swing.JTable tblPinjam;
    // End of variables declaration//GEN-END:variables
}
